#!/bin/sh

find . -type f -name '*.ti' -or -name '*.ii' -or -name '*~' -or -name '.*~' -or -name .DS_Store -or -name '.#*[0-9]*.[0-9]*' -or -name '#*#' -or -name '._?*'
find . -type f -name '*.ti' -or -name '*.ii' -or -name '*~' -or -name '.*~' -or -name .DS_Store -or -name '.#*[0-9]*.[0-9]*' -or -name '#*#' -or -name '._?*' | xargs rm -f
find . -type d -name 'ti_files'
find . -type d -name 'ti_files' | xargs rm -rf
find . -type f -name '~\$*.docx'
find . -type f -name '~\$*.docx' | xargs rm -f
rm -f core a.out *.aux *.bib.bak *.blg *.dvi *.fdb_latexmk *.fls *.synctex.gz
