#!/bin/sh

NAME=${1:-origin}
if [ "${1}" = "-h" -o "${1}" = "--help" ]; then
  echo "Usage: $(basename ${0}) [remotename]"
  exit 0
fi
URL="https://$(git remote get-url ${NAME} | sed 's%^git@%%' | sed 's%:%/%' | sed 's%.git%%')"
if [ ${URL} != "https://" ]; then
  echo "$(basename ${0}): Opening ${URL} ..."
  open ${URL}
fi
